Repository unStackOfficial/unstack.dev, pull requests merged in 2019-06, with the labels that each got.

#45 Sponsors
  images/andela.png
  images/clients/egghead.png
  images/clients/thinkster.png
  images/vanhack.png
  index.html
  js/serviceworker.js
  sw.js
  workbox-config.js
Labels: good first issue

#47 Speakers
  index.html
  past-events.html
  speakers div.txt
  speakers.html
Labels: enhancement

#48 fix schedule and created schedule div
  Schedule dev.txt
  schedule.html
Labels: enhancement

#50 removed VanHack from Sponsors
  index.html
Labels: invalid

#52 [Fix] UI Style Fixes
  css/responsive.css
  css/style.css
Labels: fix

#53 Contributors
  README.md
Labels: enhancement

#56 Sponsor
  about.html
  images/clients/cloudinary.png
  images/clients/cloudinary2.png
  index.html
Labels: enhancement

#59 Sponsor
  images/resource/obinna-unstack.png
  speakers.html
Labels: enhancement, fix

#60 Fix header responsiveness based on #55
  about.html
  contact.html
  css/responsive.css
  index.html
  mission.html
  organizers.html
  past-events.html
  schedule.html
  speakers.html
  sponsors.html
Labels: enhancement, fix

#62 Add Adora as new organizer
  README.md
  images/resource/adora.jpg
  organizers.html
Labels: good first issue

#65 [fix] sponsors section and event img
  css/style.css
  images/amp-logo.svg
  images/clients/amp-logo.png
  images/resource/about-img-2.png
  images/resource/illustration.jpg
  index.html
  speakers.html
Labels: enhancement, fix

#67 Google
  about.html
  css/style.css
  index.html
  mission.html
Labels: enhancement
