Repository unStackOfficial/unstack.dev, pull requests merged in 2019-05, with the labels that each got.

#2 now.json setup
  now.json
Labels: good first issue

#9 Pages and sections
  404.html
  about.html
  blog-single.html
  blog.html
  contact.html
  event-venue.html
  index-2.html
  index-3.html
  index-4.html
  index-5.html
  index.html
  login.html
  mission.html
  organizers.html
  past-events.html
  pricing.html
  project.html
  schedule.html
  shop-single.html
  shop.html
  shopping-cart.html
  sign-up.html
  speakers.html
  sponsors.html
Labels: fix

#10 Hero slider
  css/style.css
  index.html
Labels: enhancement, fix

#24 Pages fix
  about.html
  contact.html
  css/style.css
  index.html
  schedule.html
  speakers.html
Labels: fix

#29 Fix/contact us
  contact.html
  css/style.css
Labels: fix

#31 fix: removed banner illustration and replaced event section
  css/style.css
  images/main-slider/undraw_open_source_1qxw (1) bvg.png
  images/main-slider/user-2.png
  index.html
Labels: fix

#32 Make the contact us usable :)
  js/script.js
Labels: enhancement

#27 fix: Sponsorship Page fix
  images/andela.png
  images/vanhack.png
  sponsors.html
Labels: fix

#35 fix contact email
  js/script.js
Labels: fix

#37 Iframe
  404.html
  about.html
  coming-soon.html
  contact.html
  css/style.css
  images/resource/ademola.jpg
  images/resource/kingdom.jpg
  images/resource/marvin.jpg
  images/resource/shodipoayomide.jpg
  index.html
  js/script.js
  mission.html
  organizers.html
  past-events.html
  schedule.html
  speakers.html
  sponsors.html
Labels: enhancement, good first issue

#39 feat: meta tags feature
  about.html
  contact.html
  index.html
  mission.html
  organizers.html
  past-events.html
  schedule.html
  speakers.html
  sponsors.html
Labels: enhancement

#40 Emoticons
  about.html
  contact.html
  css/style.css
  index.html
  js/script.js
  js/validate.js
  mission.html
  now.json
  organizers.html
  past-events.html
  schedule.html
  speakers.html
  sponsors.html
Labels: enhancement

#42 Progressive Web App Support
  css/style.css
  index.html
  js/jquery.fancybox.js
  manifest.json
Labels: enhancement, good first issue
